### PR TITLE
Changed namespace reference from Microsoft.AspNetCore.Razor.Test.Inte…

### PR DESCRIPTION
**Pull request by jbagga**
…rnal to Microsoft.AspNetCore.Razor.TagHelpers.Test

cc @dougbu @NTaylorMullen

### CODE REVIEW

**Review by dougbu — CHANGES_REQUESTED** [review]
Will another iteration containing the reaction to changes in aspnet/Razor#838 but otherwise looks done.

**Comment by jbagga** [comment]
@dougbu Updated

**Review by dougbu — APPROVED** [review]
Ready to go once the related PRs are done.

**Comment by NTaylorMullen** [comment]
:shipit: once other PRs are good

**Pull request merged**
