### PR TITLE
Remove `DesignTimeHost` dependency.

### PR DESCRIPTION
**Pull request by NTaylorMullen**
- This resulted in us decoupling ourselves from the `IPlugin` interface. It's going away.
- Redesigned the `TagHelperDescriptor` resolver to be a glorified factory with a protocol. It used to serialize/deserialize messages as input because it was an `IPlugin`.

#25

### CODE REVIEW

**Comment by davidfowl** [comment]
@NTaylorMullen Looks good. It needs a bit more work to make it work outside of dnx. Like the ctor injection doesn't work anymore. This won't work on the CLI either.

**Comment by NTaylorMullen** [comment]
Updated to not use ctor injection. I'll do the `IAssemblyLoadContext` changes when I complete [this](https://github.com/aspnet/RazorTooling/issues/29)

**Pull request merged**
